#include "stb_image.h"
#include "geneticbase.h"
#include "probabilistic.h"
#include "lib/cromodistribution.h"
#include "lib/individual.h"
#include "Socket_C/socketWin.cpp"
#include <iostream>
#include <ctime>
#include <time.h>
#include <bits/stdc++.h>
#include <vector>